// Task 2.2 – OtherProduct (Books, CDs, Mobile Phones, Home Appliances)

db.OtherProduct.insertMany([
  // Books
  { product_id: 1, name: "Book 1", type: "book", short_description: "Description for Book 1", dimensions: "1x2x3 cm", shipping_weight: "0.5 kg", avg_rating: 4.1, standard_price: 10.0, retail_price: 12.0, type_specific_attribute:[ { author_name: "Michael Schofield", publisher: "Lincoln Burrows", year_of_publication: 2020, ISBN: "ISBN-00001" } ] },
  { product_id: 2, name: "Book 2", type: "book", short_description: "Description for Book 2", dimensions: "2x3x4 cm", shipping_weight: "1.0 kg", avg_rating: 4.2, standard_price: 20.0, retail_price: 24.0, type_specific_attribute:[ { author_name: "John Smith", publisher: "Theodore Bagwell", year_of_publication: 2018, ISBN: "ISBN-00002" } ] },
  { product_id: 3, name: "Book 3", type: "book", short_description: "Description for Book 3", dimensions: "3x4x5 cm", shipping_weight: "1.5 kg", avg_rating: 4.3, standard_price: 30.0, retail_price: 36.0, type_specific_attribute:[ { author_name: "Bradley Pence", publisher: "Lucy Gray", year_of_publication: 2022, ISBN: "ISBN-00003" } ] },
  { product_id: 4, name: "Book 4", type: "book", short_description: "Description for Book 4", dimensions: "4x5x6 cm", shipping_weight: "2.0 kg", avg_rating: 4.4, standard_price: 40.0, retail_price: 48.0, type_specific_attribute:[ { author_name: "James West", publisher: "Thomas Reeves", year_of_publication: 2015, ISBN: "ISBN-00004" } ] },
  { product_id: 5, name: "Book 5", type: "book", short_description: "Description for Book 5", dimensions: "5x6x7 cm", shipping_weight: "2.5 kg", avg_rating: 4.5, standard_price: 50.0, retail_price: 60.0, type_specific_attribute:[ { author_name: "Jake Furlow", publisher: "Dan Goldstein", year_of_publication: 2023, ISBN: "ISBN-00005" } ] },
  { product_id: 6, name: "Book 6", type: "book", short_description: "Description for Book 6", dimensions: "6x7x8 cm", shipping_weight: "3.0 kg", avg_rating: 4.6, standard_price: 60.0, retail_price: 72.0, type_specific_attribute:[ { author_name: "William Westfields", publisher: "Polly Thorne", year_of_publication: 2011, ISBN: "ISBN-00006" } ] },
  { product_id: 7, name: "Book 7", type: "book", short_description: "Description for Book 7", dimensions: "7x8x9 cm", shipping_weight: "3.5 kg", avg_rating: 4.7, standard_price: 70.0, retail_price: 84.0, type_specific_attribute:[ { author_name: "Arthur Row", publisher: "Billy James", year_of_publication: 2020, ISBN: "ISBN-00007" } ] },
  { product_id: 8, name: "Book 8", type: "book", short_description: "Description for Book 8", dimensions: "8x9x10 cm", shipping_weight: "4.0 kg", avg_rating: 4.8, standard_price: 80.0, retail_price: 96.0, type_specific_attribute:[ { author_name: "Donald Harris", publisher: "Martin Odegaard", year_of_publication: 2021, ISBN: "ISBN-00008" } ] },
  { product_id: 9, name: "Book 9", type: "book", short_description: "Description for Book 9", dimensions: "9x10x11 cm", shipping_weight: "4.5 kg", avg_rating: 4.9, standard_price: 90.0, retail_price: 108.0, type_specific_attribute:[ { author_name: "Gabriel Martinelli", publisher: "Mikel Arteta", year_of_publication: 2019, ISBN: "ISBN-00009" } ] },
  { product_id: 10, name: "Book 10", type: "book", short_description: "Description for Book 10", dimensions: "10x11x12 cm", shipping_weight: "5.0 kg", avg_rating: 5.0, standard_price: 100.0, retail_price: 120.0, type_specific_attribute:[ { author_name: "Roald Dahl", publisher: "Tom Harris", year_of_publication: 2020, ISBN: "ISBN-000010" } ] },

  // CDs
  { product_id: 11, name: "CD 1", type: "CD", short_description: "Description for CD 1", dimensions: "1x2 cm", shipping_weight: "0.2 kg", avg_rating: 3.5, standard_price: 5.0, retail_price: 6.5, type_specific_attribute:[ { artist_name: "Kanye West", number_of_tracks: 10, total_playing_time: "45 min", publisher: "Sony Music" } ] },
  { product_id: 12, name: "CD 2", type: "CD", short_description: "Description for CD 2", dimensions: "2x3 cm", shipping_weight: "0.4 kg", avg_rating: 3.7, standard_price: 10.0, retail_price: 13.0, type_specific_attribute:[ { artist_name: "Eminem", number_of_tracks: 12, total_playing_time: "55 min", publisher: "Universal Music" } ] },
  { product_id: 13, name: "CD 3", type: "CD", short_description: "Description for CD 3", dimensions: "3x4 cm", shipping_weight: "0.6 kg", avg_rating: 3.9, standard_price: 15.0, retail_price: 19.5, type_specific_attribute:[ { artist_name: "Drake", number_of_tracks: 15, total_playing_time: "64 min", publisher: "BE Music" } ] },
  { product_id: 14, name: "CD 4", type: "CD", short_description: "Description for CD 4", dimensions: "4x5 cm", shipping_weight: "0.8 kg", avg_rating: 4.1, standard_price: 20.0, retail_price: 26.0, type_specific_attribute:[ { artist_name: "50 Cent", number_of_tracks: 7, total_playing_time: "40 min", publisher: "Sony Music" } ] },
  { product_id: 15, name: "CD 5", type: "CD", short_description: "Description for CD 5", dimensions: "5x6 cm", shipping_weight: "1.0 kg", avg_rating: 4.3, standard_price: 25.0, retail_price: 32.5, type_specific_attribute:[ { artist_name: "Rihanna", number_of_tracks: 12, total_playing_time: "53 min", publisher: "Kobalt Music" } ] },
  { product_id: 16, name: "CD 6", type: "CD", short_description: "Description for CD 6", dimensions: "6x7 cm", shipping_weight: "1.2 kg", avg_rating: 4.5, standard_price: 30.0, retail_price: 39.0, type_specific_attribute:[ { artist_name: "The Weeknd", number_of_tracks: 21, total_playing_time: "84 min", publisher: "BE Music" } ] },
  { product_id: 17, name: "CD 7", type: "CD", short_description: "Description for CD 7", dimensions: "7x8 cm", shipping_weight: "1.4 kg", avg_rating: 4.7, standard_price: 35.0, retail_price: 45.5, type_specific_attribute:[ { artist_name: "Lil Durk", number_of_tracks: 9, total_playing_time: "42 min", publisher: "Universal Music" } ] },
  { product_id: 18, name: "CD 8", type: "CD", short_description: "Description for CD 8", dimensions: "8x9 cm", shipping_weight: "1.6 kg", avg_rating: 4.9, standard_price: 40.0, retail_price: 52.0, type_specific_attribute:[ { artist_name: "Future", number_of_tracks: 13, total_playing_time: "60 min", publisher: "K Music" } ] },
  { product_id: 19, name: "CD 9", type: "CD", short_description: "Description for CD 9", dimensions: "9x10 cm", shipping_weight: "1.8 kg", avg_rating: 5.0, standard_price: 45.0, retail_price: 58.5, type_specific_attribute:[ { artist_name: "21 Savage", number_of_tracks: 12, total_playing_time: "71 min", publisher: "K Music" } ] },
  { product_id: 20, name: "CD 10", type: "CD", short_description: "Description for CD 10", dimensions: "10x11 cm", shipping_weight: "2.0 kg", avg_rating: 5.0, standard_price: 50.0, retail_price: 65.0, type_specific_attribute:[ { artist_name: "Travis Scott", number_of_tracks: 10, total_playing_time: "50 min", publisher: "BE Music" } ] },

  // Mobile Phones
  { product_id: 21, name: "Mobile Phone 1", type: "mobile phone", short_description: "Description for Mobile Phone 1", dimensions: "10x20 cm", shipping_weight: "0.3 kg", avg_rating: 4.6, standard_price: 200.0, retail_price: 220.0, type_specific_attribute:[ { brand: "Brand A", model: "Model X1", colour: "Black", features: "4G LTE, Dual SIM, 64GB Storage" } ] },
  { product_id: 22, name: "Mobile Phone 2", type: "mobile phone", short_description: "Description for Mobile Phone 2", dimensions: "11x21 cm", shipping_weight: "0.4 kg", avg_rating: 4.7, standard_price: 300.0, retail_price: 330.0, type_specific_attribute:[ { brand: "Brand B", model: "Model Y2", colour: "Blue", features: "5G, Triple Camera, 128GB Storage" } ] },
  { product_id: 23, name: "Mobile Phone 3", type: "mobile phone", short_description: "Description for Mobile Phone 3", dimensions: "12x22 cm", shipping_weight: "0.5 kg", avg_rating: 4.8, standard_price: 400.0, retail_price: 440.0, type_specific_attribute:[ { brand: "Brand C", model: "Model Z3", colour: "Silver", features: "5G, AMOLED Display, 256GB Storage" } ] },
  { product_id: 24, name: "Mobile Phone 4", type: "mobile phone", short_description: "Description for Mobile Phone 4", dimensions: "13x23 cm", shipping_weight: "0.6 kg", avg_rating: 4.9, standard_price: 500.0, retail_price: 550.0, type_specific_attribute:[ { brand: "Brand D", model: "Model W4", colour: "Gold", features: "Foldable Display, Wireless Charging, 512GB Storage" } ] },
  { product_id: 25, name: "Mobile Phone 5", type: "mobile phone", short_description: "Description for Mobile Phone 5", dimensions: "14x24 cm", shipping_weight: "0.7 kg", avg_rating: 5.0, standard_price: 600.0, retail_price: 660.0, type_specific_attribute:[ { brand: "Brand E", model: "Model Q5", colour: "White", features: "Water Resistant, 108MP Camera, 1TB Storage" } ] },
  { product_id: 26, name: "Mobile Phone 6", type: "mobile phone", short_description: "Description for Mobile Phone 6", dimensions: "15x25 cm", shipping_weight: "0.8 kg", avg_rating: 4.6, standard_price: 700.0, retail_price: 770.0, type_specific_attribute:[ { brand: "Brand F", model: "Model V6", colour: "Black", features: "5G, Quad Camera, 512GB Storage" } ] },
  { product_id: 27, name: "Mobile Phone 7", type: "mobile phone", short_description: "Description for Mobile Phone 7", dimensions: "16x26 cm", shipping_weight: "0.9 kg", avg_rating: 4.7, standard_price: 800.0, retail_price: 880.0, type_specific_attribute:[ { brand: "Brand G", model: "Model R7", colour: "Red", features: "Wireless Charging, AMOLED Display, 256GB Storage" } ] },
  { product_id: 28, name: "Mobile Phone 8", type: "mobile phone", short_description: "Description for Mobile Phone 8", dimensions: "17x27 cm", shipping_weight: "1.0 kg", avg_rating: 4.8, standard_price: 900.0, retail_price: 990.0, type_specific_attribute:[ { brand: "Brand H", model: "Model T8", colour: "Blue", features: "Water Resistant, Dual SIM, 1TB Storage" } ] },
  { product_id: 29, name: "Mobile Phone 9", type: "mobile phone", short_description: "Description for Mobile Phone 9", dimensions: "18x28 cm", shipping_weight: "1.1 kg", avg_rating: 4.9, standard_price: 1000.0, retail_price: 1100.0, type_specific_attribute:[ { brand: "Brand I", model: "Model U9", colour: "Green", features: "Foldable Display, Wireless Charging, 108MP Camera" } ] },
  { product_id: 30, name: "Mobile Phone 10", type: "mobile phone", short_description: "Description for Mobile Phone 10", dimensions: "19x29 cm", shipping_weight: "1.2 kg", avg_rating: 5.0, standard_price: 1100.0, retail_price: 1210.0, type_specific_attribute:[ { brand: "Brand I", model: "Model U9", colour: "Green", features: "Foldable Display, Wireless Charging, 108MP Camera" } ] },

  // Home Appliances
  { product_id: 31, name: "Home Appliance 1", type: "home appliance", short_description: "Description for Home Appliance 1", dimensions: "20x30x40 cm", shipping_weight: "2.0 kg", avg_rating: 4.0, standard_price: 100.0, retail_price: 120.0, type_specific_attribute:[ { colour: "White", voltage: 220, style: "Modern" } ] },
  { product_id: 32, name: "Home Appliance 2", type: "home appliance", short_description: "Description for Home Appliance 2", dimensions: "21x31x41 cm", shipping_weight: "2.5 kg", avg_rating: 4.1, standard_price: 200.0, retail_price: 240.0, type_specific_attribute:[ { colour: "Black", voltage: 230, style: "Compact" } ] },
  { product_id: 33, name: "Home Appliance 3", type: "home appliance", short_description: "Description for Home Appliance 3", dimensions: "22x32x42 cm", shipping_weight: "3.0 kg", avg_rating: 4.2, standard_price: 300.0, retail_price: 360.0, type_specific_attribute:[ { colour: "Silver", voltage: 240, style: "Sleek" } ] },
  { product_id: 34, name: "Home Appliance 4", type: "home appliance", short_description: "Description for Home Appliance 4", dimensions: "23x33x43 cm", shipping_weight: "3.5 kg", avg_rating: 4.3, standard_price: 400.0, retail_price: 480.0, type_specific_attribute:[ { colour: "Gray", voltage: 250, style: "Industrial" } ] },
  { product_id: 35, name: "Home Appliance 5", type: "home appliance", short_description: "Description for Home Appliance 5", dimensions: "24x34x44 cm", shipping_weight: "4.0 kg", avg_rating: 4.4, standard_price: 500.0, retail_price: 600.0, type_specific_attribute:[ { colour: "Blue", voltage: 260, style: "Vintage" } ] },
  { product_id: 36, name: "Home Appliance 6", type: "home appliance", short_description: "Description for Home Appliance 6", dimensions: "25x35x45 cm", shipping_weight: "4.5 kg", avg_rating: 4.5, standard_price: 600.0, retail_price: 720.0, type_specific_attribute:[ { colour: "Red", voltage: 270, style: "Minimalist" } ] },
  { product_id: 37, name: "Home Appliance 7", type: "home appliance", short_description: "Description for Home Appliance 7", dimensions: "26x36x46 cm", shipping_weight: "5.0 kg", avg_rating: 4.6, standard_price: 700.0, retail_price: 840.0, type_specific_attribute:[ { colour: "Green", voltage: 280, style: "Eco-Friendly" } ] },
  { product_id: 38, name: "Home Appliance 8", type: "home appliance", short_description: "Description for Home Appliance 8", dimensions: "27x37x47 cm", shipping_weight: "5.5 kg", avg_rating: 4.7, standard_price: 800.0, retail_price: 960.0, type_specific_attribute:[ { colour: "Green", voltage: 280, style: "Eco-Friendly" } ] },
  { product_id: 39, name: "Home Appliance 9", type: "home appliance", short_description: "Description for Home Appliance 9", dimensions: "28x38x48 cm", shipping_weight: "6.0 kg", avg_rating: 4.8, standard_price: 900.0, retail_price: 1080.0, type_specific_attribute:[ { colour: "Brown", voltage: 300, style: "Rugged" } ] },
  { product_id: 40, name: "Home Appliance 10", type: "home appliance", short_description: "Description for Home Appliance 10", dimensions: "29x39x49 cm", shipping_weight: "6.5 kg", avg_rating: 4.9, standard_price: 1000.0, retail_price: 1200.0, type_specific_attribute:[ { colour: "Purple", voltage: 310, style: "Luxury" } ] }
]);
